# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\x12\tsrs.proto\"^\n\x0cStructHeader\x12\x15\n\rframe_counter\x18\x01 \x01(\r\x12\x0e\n\x06\x66\x65\x63_id\x18\x02 \x01(\r\x12\x15\n\rudp_timestamp\x18\x03 \x01(\r\x12\x10\n\x08overflow\x18\x04 \x01(\r\"3\n\nMarkerData\x12\x0e\n\x06vmm_id\x18\x01 \x01(\r\x12\x15\n\rsrs_timestamp\x18\x02 \x01(\x04\"\x82\x01\n\x07HitData\x12\x19\n\x11is_over_threshold\x18\x01 \x01(\x08\x12\x13\n\x0b\x63hannel_num\x18\x02 \x01(\r\x12\x0b\n\x03tdc\x18\x03 \x01(\r\x12\x0e\n\x06offset\x18\x04 \x01(\r\x12\x0e\n\x06vmm_id\x18\x05 \x01(\r\x12\x0b\n\x03\x61\x64\x63\x18\x06 \x01(\r\x12\r\n\x05\x62\x63_id\x18\x07 \x01(\r\"\x81\x01\n\x04\x44\x61ta\x12\'\n\x06header\x18\x01 \x01(\x0b\x32\x17.srs.proto.StructHeader\x12*\n\x0bmarker_data\x18\x02 \x03(\x0b\x32\x15.srs.proto.MarkerData\x12$\n\x08hit_data\x18\x03 \x03(\x0b\x32\x12.srs.proto.HitDatab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STRUCTHEADER']._serialized_start=28
  _globals['_STRUCTHEADER']._serialized_end=122
  _globals['_MARKERDATA']._serialized_start=124
  _globals['_MARKERDATA']._serialized_end=175
  _globals['_HITDATA']._serialized_start=178
  _globals['_HITDATA']._serialized_end=308
  _globals['_DATA']._serialized_start=311
  _globals['_DATA']._serialized_end=440
# @@protoc_insertion_point(module_scope)
