if(CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
    if(CMAKE_CXX_COMPILER_VERSION VERSION_LESS 19.0.0)
        message(FATAL_ERROR "Clang version must be at least 19.0.0!")
    else()
        message(STATUS "Clang version ${CMAKE_CXX_COMPILER_VERSION} is OK!")
    endif()
elseif(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
    if(CMAKE_CXX_COMPILER_VERSION VERSION_LESS 14.0.3)
        message(FATAL_ERROR "GCC version must be at least 14.0.3!")
    else()
        message(STATUS "GCC version ${CMAKE_CXX_COMPILER_VERSION} is OK!")
    endif()
elseif(CMAKE_CXX_COMPILER_ID STREQUAL "Intel")
    message(FATAL_ERROR "Intel compiler is not supportted!")
elseif(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
    message(FATAL_ERROR "MSVC compiler is not supportted yet!")
endif()
